### ISSUE TITLE
Expand Interloper AI list

### ISSUE THREAD

**Issue by InfernoGear** [Anurag-Shah/Upon-A-Crimson-Horse#102]
Custom content for interloping:
- Baluchistan (Relating to the Arghunids)
- Badakhstan (Relating to Abu Sa'id Mirza's incursions into their lands)

Also add a generalized AI interloper event for neighboring countries that _aren't_ one of the main ones. Shouldn't be a super low MTTH, though.

**Comment by AuldCetai** [comment]
AI events are done.
Generic AI - if border, strenght to Herat 40% MTTH 600 months
Definitely interlop tags - if border MTTH 120 months
Consider interloping tags - if border, strenght to Herat 60%, MTTH 120 months
BAL,BDK,ORM - player events to intervene (no loc yet)
