### ISSUE TITLE
Nerf request foreign support

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#111]
do all of the following:
- halve the bonuses
- Make 3-4 bad legitimacy events, that are in the disaster list of events
  - 300 base chance, require less than 60/50/30/10 legitimacy for the 4 events or something like that
- indicate in the tooltip for request foreign support that there will be bad events at low legitimacy
- A debuff to defensiveness and seige ability at low legitimacy, scaling from 0% at 100 legitimacy to -40% at 0 legitimacy. only applies during the disaster

**Comment by AuldCetai** [comment]
done, added the tooltip too.
