### ISSUE TITLE
Make that gahwar shad +10% all power costs less

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#112]
theres an option with +10 all power costs, +1 to all mana, which is pretty harsh of a penalty. make that idk +5% all power costs +0.25 intrest per annum

**Comment by InfernoGear** [comment]
Approved, though obviously, since Playmaker picked Muhammad Juki and the dude survived, there was a choice at all.

This would also play into more nuance with the Gawhar Shad mechanics.

**Comment by InfernoGear** [comment]
Resolved by #122. Will build upon Gawhar Shad stuff as part of a later issue.
