### ISSUE TITLE
Create a difficulty setting

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#118]
Difficulty for the succession crisis wars, creates a triggered modifier applied to all ai princes/govs. this is to make the buttons worse but, allow for the ai to survive anyways.

Easy: no buffs for AI
Normal: small ai buffs, intended way to play
Hard: large AI buffs

Buffs should include global tax, interest per annum, manpower recovery, and yearly legitimacy. no actual military quality buffs though

**Comment by AuldCetai** [comment]
done, needs testing
