### ISSUE TITLE
Add subject interaction to pull manpower from emirates

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#119]
only available during succession crisis.

add liberty desire to make that a relevant factor through the war: if you steal a lot of subjects manpower they will be unwilling to fight for you

**Comment by AuldCetai** [comment]
interactions are hardcoded.
either via decision, or move it to the govt buttons (probably the latter, but theyre pretty balanced rn, unless you want a 4th button.) also, event to dow with claimant CB if high enough LD?

**Comment by AuldCetai** [comment]
hooked it up tho govt mechanic button
