### ISSUE TITLE
the AI is unable to "build up" before the war starts, unlike the player who knows its coming

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#120]
we need something for military buildup. spawn troops in their capital up to force limit, give 2x yearly income (warchest), but no army quality buffs.

**Comment by AuldCetai** [comment]
added a hidden 10k mp and 500 gold to them to event tim.2

**Comment by AuldCetai** [comment]
ai builds to forcelimit, gets 2 years money in the bank upon SRs death
