### ISSUE TITLE
new tags becoming both governor and prince

### ISSUE THREAD

**Issue by AuldCetai** [Anurag-Shah/Upon-A-Crimson-Horse#123]
event 65 nukes country, but some of the new tags become both prince and governor
![20240226230003_1](https://github.com/Anurag-Shah/Upon-A-Crimson-Horse/assets/140598591/ff7d84c2-6e50-482f-85c7-a267f90e9895)

**Comment by Anurag-Shah** [comment]
Possible be that releasing a tag inherits your govt reform, which causes a lot of tags to have both prince and gov assigned.
