### ISSUE TITLE
UaCH.26 needs exists option triggers

### ISSUE THREAD

**Issue by Anurag-Shah** [Anurag-Shah/Upon-A-Crimson-Horse#131]
ex if Ajam doesn't exist and an ai chooses to be their vassal (like luristan), as the overlord doesn't exist luristan won't be added to war

easy fix just option trigger for exists

**Comment by InfernoGear** [comment]
Fixed by #132. Given that only Ajam has a chance of ceasing to exist before the event fires, I only added the check for them.
